name: trivia_game
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  web: ^0.5.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  http: ^1.2.0
  flutter_svg: ^2.0.14
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: JotiOne
      fonts:
        - asset: assets/font/JotiOne-Regular.ttf
    - family: Itim
      fonts:
        - asset: assets/font/Itim-Regular.ttf
  assets:
    - assets/img/backgrounds/BackgroundDefault.svg
    - assets/img/backgrounds/BackgroundDefault.png
    - assets/img/BiggerBackgroundXilogravure.svg
    - assets/img/BiggerBackgroundXilogravure.png
    - assets/img/MediumBorderXilogravure.svg
    - assets/img/MediumBorderXilogravure.png
    - assets/img/QuizLogoNordeste.svg
    - assets/img/QuizLogoNordeste.png
    - assets/img/XilogravureHomePage.svg
    - assets/img/XilogravureHomePage.png
    - assets/img/tatu.png
    - assets/img/Carranca.svg
    - assets/img/Carranca.png
    - assets/img/Cactus.svg
    - assets/img/Cactus.png
    - assets/img/CheckBox.svg
    - assets/img/CheckBox.png
    - assets/img/QuestionTextBorder.svg
    - assets/img/PositiveCheck.svg
    - assets/img/PositiveCheck.png
    - assets/img/NegativeCheck.svg
    - assets/img/NegativeCheck.png
    - assets/img/backgrounds/BackgroundMainPage.svg
    - assets/img/backgrounds/BackgroundQuestion1.png
    - assets/img/backgrounds/BackgroundQuestion2.png
    - assets/img/backgrounds/BackgroundQuestion3.png
    - assets/img/backgrounds/BackgroundQuestion4.png
    - assets/img/backgrounds/BackgroundQuestion5.png
    - assets/img/backgrounds/ResultPage.png
    - assets/audios/correct_answer.mp3
    - assets/audios/incorrect_answer.mp3
    - assets/audios/home_page.mp3


